spring:
  config:
    activate:
      on-profile:
      - docker
  application:
    name: product-service

server:
  port: 8080

logging:
   level:
      root: INFO
      se:
        magnus:
          microservices: DEBUG