server:
  port: 8001
  error:
    include-message: always

spring:
#  config:
#    activate:
#      on-profile:
#      - docker
  application:
    name: product-service



logging:
   level:
      root: INFO
      se:
        magnus:
          microservices: DEBUG