server: 
   port: 8081
   error: 
      include-message: always

spring:
   config:
      activate:
         on-profile: docker
   data:
      mongodb:
         host: localhost
         port: 27017
         database: product-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG





