server: 
   port: 8083
   error: 
      include-message: always

spring:
   datasource:
      hikari: 
         initializationFailTimeout: 60000
      url: jdbc:mysql://localhost/review-db
      username: user
      password: pwd
   jpa:
      hibernate:
         ddl-auto: update # Strongly recommend to set this property to "none" in a production environment!
   config:
      activate:
         on-profile: docker
   data:
      mongodb:
         host: localhost
         port: 27017
         database: product-db


logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

